import './globals.css'
import {Roboto } from 'next/font/google'
import Navbar from '../components/Navbar/navbar'
import Footer from '../components/Footer/footer'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
   })

export const metadata = {
  title: 'React Hooks',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="night" lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
