import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar/navbar'
import Footer from '../components/Footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="night" lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        
      </body>
    </html>
  )
}
