import './globals.css'
import {Roboto } from 'next/font/google'
import Navbar from './navbar/Navbar'
import Image from 'next/image'
import NextTopLoader from 'nextjs-toploader';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
   })

export const metadata = {
  title: "React Hooks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="night" lang="en">
      <body className={`${roboto.className} h-screen flex flex-col overflow-x-hidden`}>
      <NextTopLoader />
      <Image className='z-[-2] absolute opacity-[0.04] top-0  -left-64 '  src="/space2.png" width={700} height={700} alt="Picture of the author" />
        <Navbar />
        {children}
            <Image className='z-[10] absolute opacity-[0.033] -top-0 -right-0'  src="/space3.png" width={800} height={300} alt="Picture of the author" />
      </body>
    </html>
  );
}
